# Generated by https://quicktype.io
from datetime import datetime
from typing import Any, List, Optional, TypedDict

class WbNetwork(TypedDict):
    raw_data: Any
    id: str
    created_at: datetime

class Auth(TypedDict):
    raw_data: Any
    wb_network: List[WbNetwork]

class Environment(TypedDict):
    raw_data: Any
    id: str

class Status(TypedDict):
    raw_data: Any
    environment: Environment
    current_environment: bool

class Connection(TypedDict):
    raw_data: Any
    id: str
    start_time: int
    last_used: int
    realtime_start_time: int
    realtime_end_time: int
    status: Status

class Data(TypedDict):
    raw_data: Any
    current_platform: None
    is_orphaned: bool
    entitlement_list_steam: List[int]

class EmailVerification(TypedDict):
    raw_data: Any
    state: str

class ExternalAccounts(TypedDict):
    raw_data: Any
    pass

class Steam(TypedDict):
    raw_data: Any
    id: str
    username: str
    avatar: Optional[str]
    email: None

class Alternate(TypedDict):
    raw_data: Any
    wb_network: List[Steam]
    steam: List[Steam]

class Username(TypedDict):
    raw_data: Any
    auth: str
    username: str

class Identity(TypedDict):
    raw_data: Any
    username: str
    avatar: str
    default_username: bool
    personal_data: ExternalAccounts
    alternate: Alternate
    usernames: List[Username]
    platforms: List[str]
    current_platform: str
    is_cross_platform: bool

class OptIns(TypedDict):
    raw_data: Any
    wbplay_optin: bool

class Clan(TypedDict):
    raw_data: Any
    invitation: str

class Relationship(TypedDict):
    raw_data: Any
    follow: str

class PrivacyLevels(TypedDict):
    raw_data: Any
    presence: EmailVerification
    clan: Clan
    match: Clan
    relationship: Relationship

class ServerData(TypedDict):
    raw_data: Any
    preorder_reward_granted: bool

class WbAccount(TypedDict):
    raw_data: Any
    completed: bool
    age_category: str
    email_verified: bool

class Account(TypedDict):
    raw_data: Any
    id: str
    updated_at: datetime
    created_at: datetime
    deleted: bool
    orphaned: bool
    orphaned_reason: None
    public_id: str
    identity: Identity
    email_verification: EmailVerification
    opt_ins: OptIns
    auth: Auth
    wb_account: WbAccount
    external_accounts: ExternalAccounts
    privacy_levels: PrivacyLevels
    points: int
    state: str
    restriction_status: ExternalAccounts
    wbplay_data_synced: bool
    wbplay_identity: None
    state_data: ExternalAccounts
    locale: None
    data: Data
    server_data: ServerData
    server_owner_data: ExternalAccounts
    connections: List[Connection]
    presence_state: int
    presence: str
