# Generated by https://quicktype.io

from typing import Any, List, TypedDict

class PlayerModule(TypedDict):
    raw_data: Any
    hydra_id: str
    hydra_public_id: str
    platform: str
    platform_id: str
    platform_name: str
    wbpn_id: str
    wbpn_name: str
    background: str
    foreground: str
    ranked_season_points: int
    ranked_season_rank: int
    ranked_season_expiration: int
    ranked_season_last_played: int
    profile_exp: int
    online: bool

class PlayerModules(TypedDict):
    raw_data: Any
    player_modules: List[PlayerModule]
